### ISSUE TITLE
Please register an implementation of `org.scalafmt.interfaces.RepositoryPackageDownloaderFactory`

### ISSUE THREAD

**Issue by YannMoisan** [ghostdogpr/caliban#2977]
We are using `caliban-codegen-sbt` v3.1.0 and after bumping `sbt-scalafmt` from 2.5.2 to 2.6.0, we encountered the error below.

As a quick fix, I've added `--enableFmt false` to the generation.

```
error: .scalafmt.conf: org.scalafmt.interfaces.ScalafmtException: [v3.9.10] failed to download
Caused by: java.lang.UnsupportedOperationException: Please register an implementation of
  `org.scalafmt.interfaces.RepositoryPackageDownloaderFactory`
as a service provider, or inject it directly into an instance of
  `org.scalafmt.interfaces.Scalafmt`
using the `withRepositoryPackageDownloader` method.

	at org.scalafmt.dynamic.ScalafmtDynamic$EmptyDependencyDownloaderFactory$.create(ScalafmtDynamic.scala:106)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$WithDownloader.$anonfun$load$1(ScalafmtModuleLoader.scala:35)
	at scala.util.Try$.apply(Try.scala:213)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$WithDownloader.load(ScalafmtModuleLoader.scala:35)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.load$1(ScalafmtModuleLoader.scala:67)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.$anonfun$load$4(ScalafmtModuleLoader.scala:68)
	at scala.util.Try$.apply(Try.scala:213)
	at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:35)
	at org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.load(ScalafmtModuleLoader.scala:68)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$.$anonfun$load$1(ScalafmtConfigLoader.scala:33)
	at scala.util.Either.flatMap(Either.scala:341)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$.load(ScalafmtConfigLoader.scala:31)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.load$1(ScalafmtConfigLoader.scala:78)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.$anonfun$load$12(ScalafmtConfigLoader.scala:80)
	at scala.util.Try$.apply(Try.scala:213)
	at org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:35)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.$anonfun$load$7(ScalafmtConfigLoader.scala:80)
	at scala.util.Success.fold(Try.scala:271)
	at org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.load(ScalafmtConfigLoader.scala:75)
	at org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:74)
	at org.scalafmt.dynamic.ScalafmtDynamic.createSession(ScalafmtDynamic.scala:63)
	at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:60)
	at caliban.codegen.Formatter$.$anonfun$format$5(Formatter.scala:40)
	at scala.collection.immutable.List.map(List.scala:293)
	at caliban.codegen.Formatter$.$anonfun$format$2(Formatter.scala:40)
	at zio.ZIOCompanionVersionSpecific.$anonfun$attempt$1(ZIOCompanionVersionSpecific.scala:98)
	at zio.ZIO$.$anonfun$suspendSucceed$1(ZIO.scala:4915)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1199)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:432)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:505)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:272)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:160)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ghostdogpr** [comment]
Seems caused by https://github.com/scalameta/sbt-scalafmt/pull/437 in https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.6.0. It's unfortunate that it's triggered by the user's version and not Caliban's version. I will look into it.

**Comment by ghostdogpr** [comment]
@YannMoisan could you confirm that it works for you with snapshot `3.1.1+4-303ce43c-SNAPSHOT`? If it does I will cut a release.

**Comment by YannMoisan** [comment]
The error has changed with the snapshot

```
java.lang.NoClassDefFoundError: java/sql/Timestamp
coursier.cache.loggers.RefreshLogger$.defaultDisplay(RefreshLogger.scala:25)
coursier.cache.loggers.RefreshLogger$.create(RefreshLogger.scala:34)
org.scalafmt.dynamic.coursier.CoursierDependencyDownloader.download(CoursierDependencyDownloader.scala:22)
org.scalafmt.dynamic.ScalafmtModuleLoader$WithDownloader.$anonfun$load$1(ScalafmtModuleLoader.scala:39)
scala.util.Try$.apply(Try.scala:213)
org.scalafmt.dynamic.ScalafmtModuleLoader$WithDownloader.load(ScalafmtModuleLoader.scala:35)
org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.load$1(ScalafmtModuleLoader.scala:67)
org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.$anonfun$load$4(ScalafmtModuleLoader.scala:68)
scala.util.Try$.apply(Try.scala:213)
org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:35)
org.scalafmt.dynamic.ScalafmtModuleLoader$CachedProxy.load(ScalafmtModuleLoader.scala:68)
org.scalafmt.dynamic.ScalafmtConfigLoader$.$anonfun$load$1(ScalafmtConfigLoader.scala:33)
scala.util.Either.flatMap(Either.scala:341)
org.scalafmt.dynamic.ScalafmtConfigLoader$.load(ScalafmtConfigLoader.scala:31)
org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.load$1(ScalafmtConfigLoader.scala:78)
org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.$anonfun$load$12(ScalafmtConfigLoader.scala:80)
scala.util.Try$.apply(Try.scala:213)
org.scalafmt.dynamic.utils.ReentrantCache.getOrAddToCache(ReentrantCache.scala:35)
org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.$anonfun$load$7(ScalafmtConfigLoader.scala:80)
scala.util.Success.fold(Try.scala:271)
org.scalafmt.dynamic.ScalafmtConfigLoader$CachedProxy.load(ScalafmtConfigLoader.scala:75)
org.scalafmt.dynamic.ScalafmtDynamic.resolveConfig(ScalafmtDynamic.scala:74)
org.scalafmt.dynamic.ScalafmtDynamic.createSession(ScalafmtDynamic.scala:63)
org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:60)
caliban.codegen.Formatter$.$anonfun$format$5(Formatter.scala:40)
scala.collection.immutable.List.map(List.scala:293)
caliban.codegen.Formatter$.$anonfun$format$2(Formatter.scala:40)
zio.ZIOCompanionVersionSpecific.$anonfun$attempt$1(ZIOCompanionVersionSpecific.scala:98)
zio.ZIO$.$anonfun$suspendSucceed$1(ZIO.scala:4915)
zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1199)
zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:432)
zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:505)
zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:272)
zio.internal.FiberRuntime.run(FiberRuntime.scala:160)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by ghostdogpr** [comment]
@YannMoisan I tried another fix, there will be another snapshot (will share it later).

Just to be sure: your JVM has java.sql? (you can check with `java --list-modules | grep '^java.sql'`).

**Comment by ghostdogpr** [comment]
Here's the new snapshot: `3.1.1+5-b9f28d00-SNAPSHOT` (I was unable to reproduce your error)

**Comment by YannMoisan** [comment]
> Here's the new snapshot: `3.1.1+5-b9f28d00-SNAPSHOT` (I was unable to reproduce your error)

It works 🎉

**Comment by ghostdogpr** [comment]
Released 3.1.2! https://github.com/ghostdogpr/caliban/releases/tag/v3.1.2
